# Site settings
title: Soy de temporada
email: equipo@soydetemporada.es
url: http://soydetemporada.es
github: https://github.com/soydetemporada/
description: "Un calendario de productos de temporada fiable y transparente. Para uso cotidiano. Made in #visualizar17."
keywords: "calendario, temporada, frutas, verduras, consumo, sostenible, españa, visualizar"
meta_author: Colaboradores Journey of Food

# Backend configuration
backend_url: https://api-soydetemporada.lowfill.org

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

cookie-consent: yes

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static


# Footer settings
footer:
  copyright: Medialab Prado
  location: Equipo
  social: Redes
  credits: Contacto

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

share:
  - title: facebook
    url: http://www.facebook.com/sharer.php?u=[url]
  - title: twitter
    url: https://twitter.com/intent/tweet?text=Un%20calendario%20de%20productos%20de%20temporada%20fiable%20y%20transparente.%20Para%20uso%20cotidiano.%20Made%20in%20%23visualizar17.[url]
  - title: linkedin
    url: http://www.linkedin.com/shareArticle?url=[url]

social:
  - title: twitter
    url: https://twitter.com/soydetemporada
  - title: github
    url: https://github.com/soydetemporada/


# Credits content
credits: 'visualizar@medialab-prado.es'

collections:
  products:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product


# Build settings
markdown: kramdown
permalink: pretty

# Assets configuration
sass:
    style: compressed

# jekyll plugins
plugins:
  - jekyll-sitemap
